# Generated by Django 6.0.5 on 2026-05-07 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_number', models.CharField(max_length=100, unique=True)),
                ('service_in_datetime', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('GENERAL', 'General'), ('COMPLAINT', 'Complaint'), ('BATTERY', 'Battery'), ('CHARGER', 'Charger'), ('PAID_SERVICE_REPAIRABLE', 'Paid Service Repairable'), ('PAID_SERVICE_WARRANTY', 'Paid Service Warranty'), ('SPARES_DISPATCH', 'Spares Dispatch')], max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_job_cards', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_cards/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=20)),
                ('context', models.CharField(choices=[('INSPECTION', 'Inspection'), ('COMPLAINT', 'Complaint'), ('PART_REPLACEMENT', 'Part Replacement'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='service.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='PartsReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('NEW', 'New'), ('REPLACE', 'Replace'), ('REFURBISHED', 'Refurbished')], max_length=50)),
                ('warranty_applicable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='service.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_part', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('preferred_date', models.DateTimeField()),
                ('time_slot', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CLAIMED', 'Claimed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NEW', max_length=20)),
                ('viewed_by_admin_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_card', to='service.servicebooking'),
        ),
        migrations.CreateModel(
            name='ServiceBookingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_bookings/')),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='service.servicebooking')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Battery', 'Battery'), ('Brakes', 'Brakes'), ('Suspension', 'Suspension'), ('Charger', 'Charger'), ('Electronics', 'Electronics'), ('Display', 'Display'), ('Power', 'Power'), ('Others', 'Others')], max_length=50)),
                ('work_type', models.CharField(choices=[('PAID', 'Paid'), ('COMPLAINT', 'Complaint'), ('WARRANTY', 'Warranty')], max_length=50)),
                ('description', models.TextField()),
                ('viewed_by_admin_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='service.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK'), ('DAMAGE', 'Damage')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='service.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='service.jobcard')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
