# Generated by Django 6.0.5 on 2026-05-11 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicebooking_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsreplacement',
            name='action',
        ),
        migrations.RemoveField(
            model_name='partsreplacement',
            name='warranty_applicable',
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_parts_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_requests', to='service.servicecomplaint'),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partsreplacement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='worklog',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='service.servicecomplaint'),
        ),
        migrations.AlterField(
            model_name='partsreplacement',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_replacements', to='service.jobcard'),
        ),
        migrations.AlterField(
            model_name='partsreplacement',
            name='part_name',
            field=models.CharField(max_length=150),
        ),
    ]
