# Generated by Django 6.0.5 on 2026-05-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_partsreplacement_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='condition',
            field=models.CharField(choices=[('OK', 'OK'), ('REPAIRABLE', 'Repairable'), ('DAMAGED', 'Damaged')], max_length=20),
        ),
    ]
