# Generated by Django 6.0.5 on 2026-05-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('time_slot', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='CONFIRMED', max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
