# Generated by Django 6.0.5 on 2026-05-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testride',
            name='bike_name',
            field=models.CharField(choices=[('Flee C2', 'Flee C2'), ('Flee B1', 'Flee B1'), ('Flee B2', 'Flee B2'), ('Flee B3', 'Flee B3'), ('Flee Low Speed', 'Flee Low Speed'), ('Flee High Speed', 'Flee High Speed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testride',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=50),
        ),
        migrations.AlterField(
            model_name='testride',
            name='time_slot',
            field=models.CharField(choices=[('10:30-12 PM', '10:30-12 PM'), ('2-3 PM', '2-3 PM'), ('3-5 PM', '3-5 PM')], max_length=50),
        ),
    ]
