# Generated by Django 6.0.5 on 2026-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rides', '0002_alter_testride_bike_name_alter_testride_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testride',
            name='bike_name',
            field=models.CharField(choices=[('Flee-low-speed', 'Flee-low-speed'), ('Flee-high-speed', 'Flee-high-speed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testride',
            name='time_slot',
            field=models.CharField(choices=[('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('1:00 PM', '1:00 PM')], max_length=50),
        ),
    ]
